### ISSUE TITLE
"lambda.uploadFunction is not a function" starting with 2.1.x onward, 2.0.31 still works

### ISSUE THREAD

**Issue by mszlapa** [aws/aws-sdk-js#1050]
A code for uploading lambda function to AWS is not working in latest 2.4.6. It is required to roll back all the way to 2.0.31 to get this functionality back. 

This seems very similar to issue #916, thanks to @dmitri-bazz for idea of rolling aws-cli back as work around. Only some functionality is missing, other functions like lambda.listFunctions  are working correctly all the way to 2.4.6 

```
var AWS = require('aws-sdk');
AWS.config.update({region: 'us-east-1'});
var lambda = new AWS.Lambda();
lambda.uploadFunction(...) 

TypeError: lambda.uploadFunction is not a function

```

Environment: node v4.3.2 OS X 10.11.5, 
aws-cli installed via brew ... update-function-code works correctly via CLI.

The failing code  (gulp file) is closely following this excellent article:   https://medium.com/@AdamRNeary/a-gulp-workflow-for-amazon-lambda-61c2afd723b6#.cdax8jbiz

**Comment by chrisradek** [comment]
@mszlapa 
The `uploadFunction` operation is included in Lambda api version `2014-11-11`. The latest version, `2015-03-31` includes many newer APIs, including some that will fill the same role as `uploadFunction`.

Using `2015-03-31` (default), you can upload your lambda function code when calling [`createFunction`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#createFunction-property) or [`updateFunctionCode`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#updateFunctionCode-property). These are the preferred ways to upload your code.

It is possible to use the older Lambda API version with the latest version of the SDK as well by configuring the api version of your lambda client:
```javascript
var lambda = new AWS.Lambda({apiVersion: '2014-11-11'});
```

**Comment by mszlapa** [comment]
Thank you! 
Yes the `updateFunctionCode` seems to be working.
